let edges = [
  { from: 'edsEpisodes', to: 'edsEpisodesComplete' },
  { from: 'edsEpisodesExtra', to: 'edsEpisodesComplete' },
  { from: 'edsSeriesAsset', to: 'edsEpisodesComplete' },
  { from: 'edsSeriesAssetExtra', to: 'edsEpisodesComplete' },
  { from: 'edsEpisodesExtended', to: 'edsEpisodesComplete' },
  { from: 'edsEpisodesGenres', to: 'edsEpisodesComplete' },
  { from: 'edsEpisodesRatings', to: 'edsEpisodesComplete' },
  { from: 'edsSeries', to: 'edsSeriesExtended' },
  { from: 'edsSeriesGenres', to: 'edsSeriesExtended' },
  { from: 'edsSeriesRatings', to: 'edsSeriesExtended' },
  { from: 'edsEpisodesComplete', to: 'edsSeriesComplete' },
  { from: 'edsSeriesExtended', to: 'edsSeriesComplete' },
  { from: 'edsMovies', to: 'edsMoviesComplete' },
  { from: 'edsMoviesExtra', to: 'edsMoviesComplete' },
  { from: 'edsMoviesExtended', to: 'edsMoviesComplete' },
  { from: 'edsMoviesGenres', to: 'edsMoviesComplete' },
  { from: 'edsMoviesRatings', to: 'edsMoviesComplete' },
  { from: 'edsSportsEvent', to: 'edsSportsComplete' },
  { from: 'edsSportsEventTeams', to: 'edsSportsComplete' },
  { from: 'edsSportsLeagues', to: 'edsSportsComplete' },
  { from: 'siteInfo', to: 'final' },
  { from: 'edsSeriesComplete', to: 'final' },
  { from: 'edsMoviesComplete', to: 'final' },
  { from: 'edsSportsComplete', to: 'final' },
  { from: 'edsChannelCategories', to: 'final' },
  { from: 'edsNetworkCategories', to: 'final' },
  { from: 'edsNetwork', to: 'final' },
  { from: 'final', to: 'persistContentMetaTable' }
];
export default edges
