let nodes = {
  'siteInfo': 'siteInfo',
  'edsEpisodes': 'edsEpisodes',
  'edsEpisodesExtra': 'edsEpisodesExtra',
  'edsEpisodesExtended': 'edsEpisodesExtended',
  'edsEpisodesRatings': 'edsEpisodesRatings',
  'edsEpisodesGenres': 'edsEpisodesGenres',
  'edsSeriesAsset': 'edsSeriesAsset',
  'edsSeriesAssetExtra': 'edsSeriesAssetExtra',
  'edsSeries': 'edsSeries',
  'edsSeriesGenres': 'edsSeriesGenres',
  'edsSeriesRatings': 'edsSeriesRatings',
  'edsMovies': 'edsMovies',
  'edsMoviesExtra': 'edsMoviesExtra',
  'edsMoviesExtended': 'edsMoviesExtended',
  'edsMoviesGenres': 'edsMoviesGenres',
  'edsMoviesRatings': 'edsMoviesRatings',
  'edsSportsEvent': 'edsSportsEvent',
  'edsSportsEventTeams': 'edsSportsEventTeams',
  'edsSportsLeagues': 'edsSportsLeagues',
  'edsChannelCategories': 'edsChannelCategories',
  'edsNetworkCategories': 'edsNetworkCategories',
  'edsNetwork': 'edsNetwork',
  'edsEpisodesComplete': 'edsEpisodesComplete',
  'edsSeriesExtended': 'edsSeriesExtended',
  'edsSeriesComplete': 'edsSeriesComplete',
  'edsMoviesComplete': 'edsMoviesComplete',
  'edsSportsComplete': 'edsSportsComplete',
  'final': 'final',
  'persistContentMetaTable': 'persistContentMetaTable'
};
export default nodes
